import React,{useMemo,useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,DoorOpen,Users,GraduationCap,CalendarDays,TriangleAlert,BarChart3,Settings,Search,Bell,Plus,Clock3,MapPin,UserRound,BookOpen,CheckCircle2,XCircle,ChevronRight,Trash2,X,Menu,Radio,RefreshCw} from 'lucide-react';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import './styles.css';

type Room={id:number,name:string,capacity:number,type:string};
type Teacher={id:number,name:string,subject:string,status:'Disponível'|'Em aula'};
type Klass={id:number,name:string,students:number};
type Lesson={id:number,klass:string,subject:string,teacher:string,room:string,start:string,end:string,day:string};
type Conflict={id:number,type:string,detail:string,lessonIds:number[]};
const initialRooms:Room[]=[{id:1,name:'Sala 101',capacity:35,type:'Sala de aula'},{id:2,name:'Sala 102',capacity:35,type:'Sala de aula'},{id:3,name:'Lab. Informática',capacity:28,type:'Laboratório'},{id:4,name:'Sala Maker',capacity:24,type:'Laboratório'},{id:5,name:'Auditório',capacity:120,type:'Auditório'}];
const initialTeachers:Teacher[]=[{id:1,name:'Ana Martins',subject:'Matemática',status:'Em aula'},{id:2,name:'Carlos Lima',subject:'Física',status:'Disponível'},{id:3,name:'Mariana Souza',subject:'Linguagens',status:'Em aula'},{id:4,name:'Rafael Alves',subject:'Desenvolvimento de Sistemas',status:'Disponível'},{id:5,name:'Juliana Costa',subject:'Biologia',status:'Disponível'}];
const initialClasses:Klass[]=[{id:1,name:'1º Ano A',students:32},{id:2,name:'2º Ano A',students:30},{id:3,name:'3º Ano B',students:28},{id:4,name:'TDS 3º Série',students:26}];
const seedLessons:Lesson[]=[{id:1,klass:'3º Ano B',subject:'Matemática',teacher:'Ana Martins',room:'Sala 101',start:'13:00',end:'14:00',day:'Segunda'},{id:2,klass:'2º Ano A',subject:'Linguagens',teacher:'Mariana Souza',room:'Sala 102',start:'13:00',end:'14:00',day:'Segunda'},{id:3,klass:'TDS 3º Série',subject:'Banco de Dados',teacher:'Rafael Alves',room:'Lab. Informática',start:'14:00',end:'15:00',day:'Segunda'},{id:4,klass:'1º Ano A',subject:'Física',teacher:'Carlos Lima',room:'Sala 101',start:'14:00',end:'15:00',day:'Segunda'},{id:5,klass:'3º Ano B',subject:'Biologia',teacher:'Juliana Costa',room:'Sala 102',start:'14:00',end:'15:00',day:'Segunda'},{id:6,klass:'2º Ano A',subject:'Matemática',teacher:'Ana Martins',room:'Sala 101',start:'13:30',end:'14:30',day:'Segunda'}];
const nav=[['Visão geral',LayoutDashboard],['Salas',DoorOpen],['Professores',Users],['Turmas',GraduationCap],['Horários',CalendarDays],['Conflitos',TriangleAlert],['Métricas',BarChart3],['Configurações',Settings]] as const;
function overlaps(a:Lesson,b:Lesson){return a.day===b.day && a.start<b.end && b.start<a.end}
function detectConflicts(ls:Lesson[]):Conflict[]{const out:Conflict[]=[];let id=1;for(let i=0;i<ls.length;i++)for(let j=i+1;j<ls.length;j++){const a=ls[i],b=ls[j];if(!overlaps(a,b))continue;if(a.room===b.room)out.push({id:id++,type:'Conflito de sala',detail:`${a.room} foi reservada para ${a.klass} e ${b.klass} no mesmo período.`,lessonIds:[a.id,b.id]});if(a.teacher===b.teacher)out.push({id:id++,type:'Conflito de professor',detail:`${a.teacher} aparece em duas aulas simultâneas.`,lessonIds:[a.id,b.id]});if(a.klass===b.klass)out.push({id:id++,type:'Conflito de turma',detail:`${a.klass} possui duas aulas simultâneas.`,lessonIds:[a.id,b.id]})}return out}
function App(){
 const [page,setPage]=useState('Visão geral'); const [rooms,setRooms]=useState<Room[]>(()=>JSON.parse(localStorage.getItem('ei_rooms')||'null')||initialRooms); const [teachers,setTeachers]=useState<Teacher[]>(()=>JSON.parse(localStorage.getItem('ei_teachers')||'null')||initialTeachers); const [classes,setClasses]=useState<Klass[]>(()=>JSON.parse(localStorage.getItem('ei_classes')||'null')||initialClasses); const [lessons,setLessons]=useState<Lesson[]>(()=>JSON.parse(localStorage.getItem('ei_lessons')||'null')||seedLessons); const [modal,setModal]=useState<string|null>(null); const [query,setQuery]=useState(''); const [mobile,setMobile]=useState(false);
 useEffect(()=>{localStorage.setItem('ei_rooms',JSON.stringify(rooms));localStorage.setItem('ei_teachers',JSON.stringify(teachers));localStorage.setItem('ei_classes',JSON.stringify(classes));localStorage.setItem('ei_lessons',JSON.stringify(lessons))},[rooms,teachers,classes,lessons]);
 const conflicts=useMemo(()=>detectConflicts(lessons),[lessons]); const nowActive=lessons.filter(x=>x.start<='14:00'&&x.end>'14:00').length; const occupied=new Set(lessons.filter(x=>x.start<='14:00'&&x.end>'14:00').map(x=>x.room)).size;
 const metrics=[{name:'Salas',valor:rooms.length},{name:'Professores',valor:teachers.length},{name:'Turmas',valor:classes.length},{name:'Aulas',valor:lessons.length},{name:'Conflitos',valor:conflicts.length}];
 const filtered=(arr:any[])=>arr.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
 function reset(){localStorage.clear();setRooms(initialRooms);setTeachers(initialTeachers);setClasses(initialClasses);setLessons(seedLessons)}
 return <div className="app"><aside className={mobile?'side open':'side'}><div className="brand"><div className="brandmark">EI</div><div><b>Escola</b><span>Inteligente</span></div></div><div className="live"><i/> Sistema online</div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setMobile(false)}}><I size={19}/>{n}{n==='Conflitos'&&conflicts.length>0?<em>{conflicts.length}</em>:null}</button>)}</nav><div className="sidefoot"><div className="avatar">AD</div><div><b>Administrador</b><span>Gestão escolar</span></div></div></aside><main><header><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button><div><h1>{page}</h1><p>{page==='Visão geral'?'Acompanhe a operação da escola em tempo real.':'Gerencie e acompanhe os dados da escola.'}</p></div><div className="headright"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..."/></div><button className="icon"><Bell size={19}/><i/></button><div className="date"><CalendarDays size={18}/><span>Hoje<br/><b>28 set. 2026</b></span></div></div></header><section className="content">
 {page==='Visão geral'&&<><div className="hero"><div><span className="eyebrow"><Radio size={14}/> OPERAÇÃO EM TEMPO REAL</span><h2>Boa tarde, equipe gestora.</h2><p>Veja rapidamente o que está acontecendo na escola e antecipe conflitos.</p></div><button className="primary" onClick={()=>setModal('lesson')}><Plus size={18}/> Programar aula</button></div><div className="cards"><Stat icon={DoorOpen} label="Salas em uso" value={`${occupied}/${rooms.length}`} sub={`${Math.round(occupied/rooms.length*100)||0}% de ocupação`}/><Stat icon={Users} label="Professores em aula" value={String(nowActive)} sub={`${teachers.filter(t=>t.status==='Disponível').length} disponíveis`}/><Stat icon={GraduationCap} label="Turmas acompanhadas" value={String(classes.length)} sub={`${classes.reduce((a,c)=>a+c.students,0)} alunos`}/><Stat icon={TriangleAlert} label="Conflitos detectados" value={String(conflicts.length)} sub={conflicts.length?'Requer atenção':'Tudo organizado'} warn={!!conflicts.length}/></div><div className="grid2"><Panel title="Aulas agora" action="Ver horários" onAction={()=>setPage('Horários')}><div className="lessonlist">{lessons.slice(0,4).map(l=><LessonRow key={l.id} l={l}/>)}</div></Panel><Panel title="Situação das salas" action="Gerenciar" onAction={()=>setPage('Salas')}><div className="roomgrid">{rooms.map(r=>{let busy=[...lessons].reverse().find(l=>l.room===r.name&&l.start<='14:00'&&l.end>'14:00');return <div className="room" key={r.id}><div><DoorOpen size={18}/><b>{r.name}</b></div><span className={busy?'busy':'free'}>{busy?'Em uso':'Livre'}</span><small>{busy?`${busy.klass} · até ${busy.end}`:`${r.capacity} lugares`}</small></div>})}</div></Panel></div><div className="grid2 lower"><Panel title="Alertas inteligentes" action="Ver todos" onAction={()=>setPage('Conflitos')}>{conflicts.length?conflicts.slice(0,3).map(c=><div className="alert" key={c.id}><TriangleAlert/><div><b>{c.type}</b><p>{c.detail}</p></div><ChevronRight/></div>):<Empty text="Nenhum conflito detectado."/>}</Panel><Panel title="Próximas aulas"><div className="timeline">{lessons.slice(2,6).map(l=><LessonRow key={l.id} l={l}/>)}</div></Panel></div></>}
 {page==='Salas'&&<CrudHeader title="Salas" text="Acompanhe disponibilidade, capacidade e utilização." add="Nova sala" onAdd={()=>setModal('room')}/>} {page==='Salas'&&<div className="tablewrap"><table><thead><tr><th>Sala</th><th>Tipo</th><th>Capacidade</th><th>Status atual</th><th></th></tr></thead><tbody>{filtered(rooms).map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.type}</td><td>{r.capacity} pessoas</td><td><span className="pill free">Disponível/monitorada</span></td><td><button className="trash" onClick={()=>setRooms(rooms.filter(x=>x.id!==r.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}
 {page==='Professores'&&<><CrudHeader title="Professores" text="Disponibilidade e acompanhamento da equipe docente." add="Novo professor" onAdd={()=>setModal('teacher')}/><div className="people">{filtered(teachers).map(t=><div className="person" key={t.id}><div className="personavatar">{t.name.split(' ').map((x:string)=>x[0]).slice(0,2)}</div><div><h3>{t.name}</h3><p>{t.subject}</p><span className={t.status==='Em aula'?'pill busy':'pill free'}>{t.status}</span></div><button className="trash" onClick={()=>setTeachers(teachers.filter(x=>x.id!==t.id))}><Trash2 size={16}/></button></div>)}</div></>}
 {page==='Turmas'&&<><CrudHeader title="Turmas" text="Turmas acompanhadas pelo painel inteligente." add="Nova turma" onAdd={()=>setModal('class')}/><div className="people">{filtered(classes).map(c=><div className="person" key={c.id}><div className="personavatar"><GraduationCap/></div><div><h3>{c.name}</h3><p>{c.students} alunos</p><span className="pill free">Ativa</span></div><button className="trash" onClick={()=>setClasses(classes.filter(x=>x.id!==c.id))}><Trash2 size={16}/></button></div>)}</div></>}
 {page==='Horários'&&<><CrudHeader title="Programação de horários" text="Organize aulas, salas, turmas e professores." add="Programar aula" onAdd={()=>setModal('lesson')}/><div className="tablewrap"><table><thead><tr><th>Dia</th><th>Horário</th><th>Turma</th><th>Disciplina</th><th>Professor</th><th>Sala</th><th></th></tr></thead><tbody>{filtered(lessons).map(l=><tr key={l.id}><td>{l.day}</td><td><b>{l.start} – {l.end}</b></td><td>{l.klass}</td><td>{l.subject}</td><td>{l.teacher}</td><td>{l.room}</td><td><button className="trash" onClick={()=>setLessons(lessons.filter(x=>x.id!==l.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></>}
 {page==='Conflitos'&&<><CrudHeader title="Central de conflitos" text="Conflitos são identificados automaticamente ao cruzar horários, salas, professores e turmas."/><div className="conflicts">{conflicts.length?conflicts.map(c=><div className="conflict" key={c.id}><div className="conficon"><TriangleAlert/></div><div><span>DETECTADO AUTOMATICAMENTE</span><h3>{c.type}</h3><p>{c.detail}</p><small>Aulas relacionadas: #{c.lessonIds.join(' e #')}</small></div></div>):<Empty text="Nenhum conflito. A programação está consistente."/>}</div></>}
 {page==='Métricas'&&<><CrudHeader title="Métricas de desempenho" text="Indicadores definidos no projeto para apoiar a tomada de decisão."/><div className="metriccards">{metrics.map(m=><div className="metric" key={m.name}><span>{m.name}</span><b>{m.valor}</b></div>)}</div><div className="chartbox"><h3>Visão operacional</h3><ResponsiveContainer width="100%" height={320}><BarChart data={metrics}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="valor" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></>}
 {page==='Configurações'&&<><CrudHeader title="Configurações" text="Preferências locais da demonstração."/><div className="settingsbox"><h3>Dados de demonstração</h3><p>Os dados são salvos no navegador automaticamente. Você pode restaurar a base inicial quando quiser.</p><button className="secondary" onClick={reset}><RefreshCw size={17}/> Restaurar dados iniciais</button><h3>Sobre</h3><p>Escola Inteligente · Painel de controle para monitoramento e programação de salas, professores, turmas e horários.</p></div></>}
 </section></main>{modal&&<Modal type={modal} close={()=>setModal(null)} rooms={rooms} teachers={teachers} classes={classes} onRoom={(x:any)=>setRooms([...rooms,{...x,id:Date.now()}])} onTeacher={(x:any)=>setTeachers([...teachers,{...x,id:Date.now(),status:'Disponível'}])} onClass={(x:any)=>setClasses([...classes,{...x,id:Date.now()}])} onLesson={(x:any)=>setLessons([...lessons,{...x,id:Date.now()}])}/>}</div>
}
function Stat({icon:I,label,value,sub,warn=false}:any){return <div className={warn?'stat warn':'stat'}><div className="staticon"><I/></div><div><span>{label}</span><b>{value}</b><small>{sub}</small></div></div>}
function Panel({title,action,onAction,children}:any){return <div className="panel"><div className="panelhead"><h3>{title}</h3>{action&&<button onClick={onAction}>{action}<ChevronRight size={16}/></button>}</div>{children}</div>}
function LessonRow({l}:any){return <div className="lesson"><div className="time">{l.start}</div><div className="line"/><div className="lessoninfo"><b>{l.subject}</b><span><GraduationCap size={14}/>{l.klass}</span><span><UserRound size={14}/>{l.teacher}</span></div><div className="place"><MapPin size={14}/>{l.room}</div></div>}
function CrudHeader({title,text,add,onAdd}:any){return <div className="crudhead"><div><h2>{title}</h2><p>{text}</p></div>{add&&<button className="primary" onClick={onAdd}><Plus size={18}/>{add}</button>}</div>}
function Empty({text}:any){return <div className="empty"><CheckCircle2/><b>{text}</b></div>}
function Modal({type,close,rooms,teachers,classes,onRoom,onTeacher,onClass,onLesson}:any){const [f,setF]=useState<any>({day:'Segunda',start:'13:00',end:'14:00',room:rooms[0]?.name,teacher:teachers[0]?.name,klass:classes[0]?.name,type:'Sala de aula',capacity:30,students:30});const set=(k:string,v:any)=>setF({...f,[k]:v});const submit=(e:any)=>{e.preventDefault();if(type==='room')onRoom({name:f.name,capacity:+f.capacity,type:f.type});if(type==='teacher')onTeacher({name:f.name,subject:f.subject});if(type==='class')onClass({name:f.name,students:+f.students});if(type==='lesson')onLesson(f);close()};return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><div className="modalhead"><div><span>ESCOLA INTELIGENTE</span><h2>{type==='lesson'?'Programar nova aula':type==='room'?'Cadastrar sala':type==='teacher'?'Cadastrar professor':'Cadastrar turma'}</h2></div><button type="button" onClick={close}><X/></button></div>{type==='room'&&<><Field label="Nome da sala" on={v=>set('name',v)} required/><Field label="Capacidade" type="number" value="30" on={v=>set('capacity',v)}/><Select label="Tipo" values={['Sala de aula','Laboratório','Auditório','Sala Maker']} on={v=>set('type',v)}/></>}{type==='teacher'&&<><Field label="Nome" on={v=>set('name',v)} required/><Field label="Disciplina / área" on={v=>set('subject',v)} required/></>}{type==='class'&&<><Field label="Nome da turma" on={v=>set('name',v)} required/><Field label="Quantidade de alunos" type="number" value="30" on={v=>set('students',v)}/></>}{type==='lesson'&&<><div className="formgrid"><Select label="Turma" values={classes.map((x:any)=>x.name)} on={v=>set('klass',v)}/><Field label="Disciplina" on={v=>set('subject',v)} required/><Select label="Professor" values={teachers.map((x:any)=>x.name)} on={v=>set('teacher',v)}/><Select label="Sala" values={rooms.map((x:any)=>x.name)} on={v=>set('room',v)}/><Select label="Dia" values={['Segunda','Terça','Quarta','Quinta','Sexta']} on={v=>set('day',v)}/><Field label="Início" type="time" value="13:00" on={v=>set('start',v)}/><Field label="Fim" type="time" value="14:00" on={v=>set('end',v)}/></div></>}<div className="modalfoot"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">Salvar</button></div></form></div>}
function Field({label,type='text',value,on,required=false}:any){return <label className="field"><span>{label}</span><input type={type} defaultValue={value} required={required} onChange={e=>on(e.target.value)}/></label>}
function Select({label,values,on}:any){return <label className="field"><span>{label}</span><select onChange={e=>on(e.target.value)}>{values.map((x:string)=><option key={x}>{x}</option>)}</select></label>}
createRoot(document.getElementById('root')!).render(<App/>);
